# Generated by Django 4.1.1 on 2023-08-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_musicians_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="movie's name")),
                ('location', models.URLField(verbose_name="movie's url")),
                ('image', models.TextField(verbose_name="movie's poster")),
            ],
        ),
        migrations.DeleteModel(
            name='Musicians',
        ),
    ]
